/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Interview API
 * Documentation for interview endpoints
 * OpenAPI spec version: 1.0.0
 */
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import { useCallback } from "react";

import type { ErrorType } from "../../mutator/useCustomInstance";
import { useCustomInstance } from "../../mutator/useCustomInstance";
import type { UserDto } from "../../types";

/**
 * @summary Get User Profile
 */
export const useGetUserProfileHook = () => {
  const getUserProfile = useCustomInstance<UserDto>();

  return useCallback(
    (signal?: AbortSignal) => {
      return getUserProfile({ url: `https://interview-api-8icc.onrender.com/api/user`, method: "GET", signal });
    },
    [getUserProfile],
  );
};

export const getGetUserProfileQueryKey = () => {
  return [`https://interview-api-8icc.onrender.com/api/user`] as const;
};

export const useGetUserProfileQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserProfileQueryKey();

  const getUserProfile = useGetUserProfileHook();

  const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>> = ({ signal }) =>
    getUserProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserProfileQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>>;
export type GetUserProfileQueryError = ErrorType<unknown>;

export function useGetUserProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>,
  TError = ErrorType<unknown>,
>(options: {
  query: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>, TError, TData>,
      "initialData"
    >;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetUserProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>, TError, TData>,
      "initialData"
    >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetUserProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get User Profile
 */

export function useGetUserProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetUserProfileHook>>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = useGetUserProfileQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
