/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Interview API
 * Documentation for interview endpoints
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useCallback } from "react";
import type { GetApiProducts200Item } from "../../types";
import { useCustomInstance } from "../../mutator/use-custom-instance";
import type { ErrorType } from "../../mutator/use-custom-instance";

/**
 * @summary Get top sales products
 */
export const useGetApiProductsHook = () => {
  const getApiProducts = useCustomInstance<GetApiProducts200Item[]>();

  return useCallback(
    (signal?: AbortSignal) => {
      return getApiProducts({ url: `https://interview-api-8icc.onrender.com/api/products`, method: "GET", signal });
    },
    [getApiProducts],
  );
};

export const getGetApiProductsQueryKey = () => {
  return [`https://interview-api-8icc.onrender.com/api/products`] as const;
};

export const useGetApiProductsQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiProductsQueryKey();

  const getApiProducts = useGetApiProductsHook();

  const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>> = ({ signal }) =>
    getApiProducts(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiProductsQueryResult = NonNullable<Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>>;
export type GetApiProductsQueryError = ErrorType<void>;

export function useGetApiProducts<
  TData = Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>,
  TError = ErrorType<void>,
>(options: {
  query: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>, TError, TData>> &
    Pick<
      DefinedInitialDataOptions<Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>, TError, TData>,
      "initialData"
    >;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiProducts<
  TData = Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>, TError, TData>> &
    Pick<
      UndefinedInitialDataOptions<Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>, TError, TData>,
      "initialData"
    >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useGetApiProducts<
  TData = Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
/**
 * @summary Get top sales products
 */

export function useGetApiProducts<
  TData = Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetApiProductsHook>>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = useGetApiProductsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
